### ISSUE TITLE
Error processing platform spook.repairs

### ISSUE THREAD

**Issue by gieljnssns** [frenck/spook#13]
However, I'm not your homie
Here is an issue,
```
Logger: homeassistant.helpers.integration_platform
Source: components/repairs/issue_handler.py:113
First occurred: 12:58:19 (2 occurrences)
Last logged: 12:58:19

Error processing platform spook.repairs
Error processing platform hassio.repairs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 51, in _async_process_single_integration_platform_component
    await integration_platform.process_platform(hass, component_name, platform)
  File "/usr/src/homeassistant/homeassistant/components/repairs/issue_handler.py", line 113, in _register_repairs_platform
    raise HomeAssistantError(f"Invalid repairs platform {platform}")
homeassistant.exceptions.HomeAssistantError: Invalid repairs platform <module 'custom_components.spook.repairs' from '/config/custom_components/spook/repairs/__init__.py'>

```

**Comment by frenck** [comment]
Interesting, haven't noticed it being picked up as an integration platform.

This needs addressing. Will take a look.

../Frenck
