### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by holdestmade** [frenck/spook#188]
Getting this on v0.13.131314

Logger: custom_components.spook
Source: custom_components/spook/repairs/lovelace_unknown_entity_references.py:264
Integration: Spook ([documentation](https://github.com/frenck/spook), [issues](https://github.com/frenck/spook/issues))
First occurred: 16:32:14 (8 occurrences)
Last logged: 16:34:12

Unexpected exception from <function AbstractSpookRepair.async_activate.<locals>._async_inspect at 0xffff5adcbd00>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 117, in _handle_timer_finish
    await task
  File "/config/custom_components/spook/repairs/__init__.py", line 130, in _async_inspect
    await self.async_inspect()
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 108, in async_inspect
    for entity_id in self.__async_extract_entities(config)
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 159, in __async_extract_entities
    entities.update(self.__async_extract_entities_from_card(card))
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 225, in __async_extract_entities_from_card
    entities.update(self.__async_extract_entities_from_card(card))
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 235, in __async_extract_entities_from_card
    entities.update(self.__async_extract_entities_from_element(element))
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 288, in __async_extract_entities_from_element
    entities.update(self.__async_extract_entities_from_actions(config))
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 255, in __async_extract_entities_from_actions
    entities.update(self.__async_extract_entities_from_action(action))
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 264, in __async_extract_entities_from_action
    (target := config.get(key))
AttributeError: 'str' object has no attribute 'get'

**Comment by frenck** [comment]
Do you have any `action:` in your YAML dashboards that have a string as a value?

**Comment by holdestmade** [comment]
The only `action`: I can see is navigate, toggle, call-service and none. I did have a few null but have replaced them with none.

I do have a few `action: double_tap` but they are for custom restriction card

**Comment by Mariusthvdb** [comment]
dont want to be daft, but what is the solution to this? Does Spook need to exclude those in the scan, or do we need to do anything in the action yaml...

**Comment by frenck** [comment]
No, this can be handled by Spook. I wasn't able to take into account all the custom stuff out there writing this 😉 

Will maybe pick it up tomorrow (or something).
