### ISSUE TITLE
Unexpected exception from <function AbstractSpookRepair.async_activate.<locals>._async_inspect at 0x7f81b5b04ca0>

### ISSUE THREAD

**Issue by C0rish** [frenck/spook#217]
Logger: custom_components.spook
Source: custom_components/spook/repairs/lovelace_unknown_entity_references.py:264
Integration: Spook ([documentation](https://github.com/frenck/spook), [issues](https://github.com/frenck/spook/issues))
First occurred: 13:53:04 (1 occurrences)
Last logged: 13:53:04

Unexpected exception from <function AbstractSpookRepair.async_activate.<locals>._async_inspect at 0x7f81b5b04ca0>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 117, in _handle_timer_finish
    await task
  File "/config/custom_components/spook/repairs/__init__.py", line 130, in _async_inspect
    await self.async_inspect()
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 108, in async_inspect
    for entity_id in self.__async_extract_entities(config)
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 159, in __async_extract_entities
    entities.update(self.__async_extract_entities_from_card(card))
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 225, in __async_extract_entities_from_card
    entities.update(self.__async_extract_entities_from_card(card))
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 225, in __async_extract_entities_from_card
    entities.update(self.__async_extract_entities_from_card(card))
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 213, in __async_extract_entities_from_card
    entities.update(self.__async_extract_entities_from_actions(config))
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 255, in __async_extract_entities_from_actions
    entities.update(self.__async_extract_entities_from_action(action))
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 264, in __async_extract_entities_from_action
    (target := config.get(key))
AttributeError: 'str' object has no attribute 'get'

**Comment by C0rish** [comment]
I'm using HA 2023.5.4 with the latest spook version: v0.13.131314

**Comment by C0rish** [comment]
It's definitely not a one time error, it occurs regularly:


Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.spook
Source: custom_components/spook/repairs/lovelace_unknown_entity_references.py:264
Integration: Spook (documentation, issues)
First occurred: 6. Juni 2023 um 13:53:04 (66 occurrences)
Last logged: 08:14:31

Unexpected exception from <function AbstractSpookRepair.async_activate.<locals>._async_inspect at 0x7f81b5b04ca0>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 117, in _handle_timer_finish
    await task
  File "/config/custom_components/spook/repairs/__init__.py", line 130, in _async_inspect
    await self.async_inspect()
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 108, in async_inspect
    for entity_id in self.__async_extract_entities(config)
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 159, in __async_extract_entities
    entities.update(self.__async_extract_entities_from_card(card))
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 225, in __async_extract_entities_from_card
    entities.update(self.__async_extract_entities_from_card(card))
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 225, in __async_extract_entities_from_card
    entities.update(self.__async_extract_entities_from_card(card))
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 213, in __async_extract_entities_from_card
    entities.update(self.__async_extract_entities_from_actions(config))
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 255, in __async_extract_entities_from_actions
    entities.update(self.__async_extract_entities_from_action(action))
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 264, in __async_extract_entities_from_action
    (target := config.get(key))
AttributeError: 'str' object has no attribute 'get'

**Comment by pplucky** [comment]
Same thing happens with [v0.14.0](https://github.com/frenck/spook/tree/v0.14.0) on HA 2023.6.1...

**Comment by C0rish** [comment]
My specific error hasn't occurred for a day after updating to Spook 14 and HA 2023.6.1.

I'll keep watching

**Comment by frenck** [comment]
Is this still gone in V1.0.0+ of this integration?

../Frenck

**Comment by C0rish** [comment]
Haven't seen this error since you fixed it. Also not with version 1.0.0 or above.
