### ISSUE TITLE
Service "homeassistant.disable_entity" error with entity without unique_id

### ISSUE THREAD

**Issue by alesoft73** [frenck/spook#218]
I have test to disable and enable the device_tracker with service "homeassistant.disable_entity" or "enable".

service: homeassistant.disable_entity
data:
  entity_id: device_tracker.test_1

The service don't work with device_tracker don't have unique_id  ex: "ble tracker" 
I have this error:
139955523604528] Error handling message: Unknown error (unknown_error) Alesoft73 from 95.232.27.3 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 647, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1533, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 410, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 454, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 477, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 452, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 685, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1849, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1889, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 874, in admin_handler
    await result
  File "/config/custom_components/spook/services/homeassistant_disable_entity.py", line 28, in async_handle_service
    entity_registry.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 884, in async_update_entity
    return self._async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 760, in _async_update_entity
    old = self.entities[entity_id]
  File "/usr/local/lib/python3.10/collections/__init__.py", line 1106, in __getitem__
    raise KeyError(key)
KeyError: 'device_tracker.test_1'

Many thanks ;)

**Comment by frenck** [comment]
Correct, there is no way to disable such entities.

../Frenck
