### ISSUE TITLE
Unexpected exception from <function AbstractSpookRepair.async_activate.<locals>._async_inspect at 0x7f4f82ede0>

### ISSUE THREAD

**Issue by pplucky** [frenck/spook#222]
Since update to 2023.6.x, I get errors like the following, around every minute:
```Logger: custom_components.spook
Source: custom_components/spook/repairs/lovelace_unknown_entity_references.py:217 
Integration: Spook ([documentation](https://github.com/frenck/spook), [issues](https://github.com/frenck/spook/issues)) 
First occurred: 14:54:38 (22 occurrences) 
Last logged: 15:23:49

Unexpected exception from <function AbstractSpookRepair.async_activate.<locals>._async_inspect at 0x7f4f82ede0>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 117, in _handle_timer_finish
    await task
  File "/config/custom_components/spook/repairs/__init__.py", line 130, in _async_inspect
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 108, in async_inspect
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 156, in __async_extract_entities
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 215, in __async_extract_entities_from_card
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 218, in __async_extract_entities_from_card
  File "/config/custom_components/spook/repairs/lovelace_unknown_entity_references.py", line 217, in __async_extract_entities_from_card
TypeError: 'NoneType' object is not iterable
```

Anything else that I can provide to help fix this issue?

**Comment by pplucky** [comment]
Repeated from #217
