### ISSUE TITLE
Error updating to version 1.0.0

### ISSUE THREAD

**Issue by dhover** [frenck/spook#286]
### What version of Spook are you using?

0.14.0

### What version of Home Assistant are you using?

2023.8.1

### The problem

Updating from 0.14.0 to 1.0.0 doesn't work. 

### Anything in the logs? Paste it here!

```plain text
2023-08-10 12:10:55.975 ERROR (MainThread) [custom_components.hacs] <Integration frenck/spook> Download was not completed
2023-08-10 12:10:56.014 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139685429455168] Error handling message: Unknown error (unknown_error) xxxxxx from x.x.x.x (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
await func(hass, connection, msg)
File "/config/custom_components/hacs/websocket/repository.py", line 216, in hacs_repository_download
await repository.async_install()
File "/config/custom_components/hacs/repositories/base.py", line 899, in async_install
await self.async_install_repository()
File "/config/custom_components/hacs/repositories/base.py", line 995, in async_install_repository
raise HacsException("Could not download, see log for details")
custom_components.hacs.exceptions.HacsException: Could not download, see log for details
```

**Comment by frenck** [comment]
Thanks! Also saw a report on Twitter/X(or whatever it is called nowadays), unsure what is going on. Will investigate.

../Frenck

**Comment by dhover** [comment]
It says "see log for details". What log file is meant? HA Log?

**Comment by phellarv** [comment]
Same error here: 
https://privatebin.duckboot.net/?8faa80e051f22f54#C1WhaCNHVgz1WmVBDndzZrB8nBd9dpzvmi2bZRicaxkt

**Comment by frenck** [comment]
> It says "see log for details". What log file is meant? HA Log?

I don't know, HACS is sending that message :S

**Comment by frenck** [comment]
Hmmz I think I understand what is happening. I've updated the existing release.

Could you try downloading it again? (I hope caching doesn't kick in there). 

../Frenck

**Comment by dhover** [comment]
Now it works!

**Comment by frenck** [comment]
Seems like HACS is struggling with the new signature file I've shipped this release.

Removed it manually from the release, and will remove it from the release process for now.

../Frenck

**Comment by dhover** [comment]
Ok, I understand. Issue solved!
Thanks.

**Comment by dhover** [comment]
Closed.

**Comment by frenck** [comment]
👍  Keeping this issue open, as I need to resolve it in the codebase (to prevent is from happening again).

../Frenck

**Comment by phellarv** [comment]
Work for me too now. Good Job resolving this issue so fast.
