### ISSUE TITLE
unhashable type: 'dict'

### ISSUE THREAD

**Issue by emufan** [frenck/spook#318]
### What version of Spook are you using?

1.1.0

### What version of Home Assistant are you using?

2023.08.2

### The problem

Errors in Log.

If anything more to provide, I'll do so.

### Anything in the logs? Paste it here!

```plain text
2023-08-14 18:55:40.898 ERROR (MainThread) [custom_components.spook] Unexpected exception from <function AbstractSpookRepair.async_activate.<locals>._async_inspect at 0xffff74683420>
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 116, in _handle_timer_finish
await task
File "/config/custom_components/spook/repairs.py", line 126, in _async_inspect
await self.async_inspect()
File "/config/custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py", line 112, in async_inspect
for entity_id in self.__async_extract_entities(config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py", line 159, in __async_extract_entities
entities.update(self.__async_extract_entities_from_badge(badge))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py", line 207, in __async_extract_entities_from_badge
return set(config["entities"])
^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
2023-08-14 18:57:04.059 DEBUG (MainThread) [custom_components.spook] Spook is inspecting: lovelace_unknown_entity_references
2023-08-14 18:57:04.062 DEBUG (MainThread) [custom_components.spook] Config for dashboard lovelace not found, skipping
2023-08-14 18:57:04.063 DEBUG (MainThread) [custom_components.spook] Spook is inspecting: automation_unknown_entity_references
2023-08-14 18:57:04.067 DEBUG (MainThread) [custom_components.spook] Spook is inspecting: script_unknown_entity_references
2023-08-14 18:57:04.071 ERROR (MainThread) [custom_components.spook] Unexpected exception from <function AbstractSpookRepair.async_activate.<locals>._async_inspect at 0xffff74683420>
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 116, in _handle_timer_finish
await task
File "/config/custom_components/spook/repairs.py", line 126, in _async_inspect
await self.async_inspect()
File "/config/custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py", line 112, in async_inspect
for entity_id in self.__async_extract_entities(config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py", line 159, in __async_extract_entities
entities.update(self.__async_extract_entities_from_badge(badge))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py", line 207, in __async_extract_entities_from_badge
return set(config["entities"])
^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
```

**Comment by frenck** [comment]
Thanks!

The details help a lot, I can work with that 👍 

../Frenck
