### ISSUE TITLE
unhashable type: 'dict' no.2

### ISSUE THREAD

**Issue by emufan** [frenck/spook#324]
### What version of Spook are you using?

v.1.1.1

### What version of Home Assistant are you using?

2023-08.2

### The problem

Follow up from https://github.com/frenck/spook/issues/318

Error-type still there.

### Anything in the logs? Paste it here!

```plain text
2023-08-16 17:52:28.263 DEBUG (MainThread) [custom_components.spook] Spook is inspecting: lovelace_unknown_entity_references
2023-08-16 17:52:28.267 DEBUG (MainThread) [custom_components.spook] Config for dashboard lovelace not found, skipping
2023-08-16 17:52:28.267 ERROR (MainThread) [custom_components.spook] Unexpected exception from <function AbstractSpookRepair.async_activate.<locals>._async_inspect at 0xffff634a5580>
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 116, in _handle_timer_finish
await task
File "/config/custom_components/spook/repairs.py", line 126, in _async_inspect
await self.async_inspect()
File "/config/custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py", line 112, in async_inspect
for entity_id in self.__async_extract_entities(config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py", line 159, in __async_extract_entities
entities.update(self.__async_extract_entities_from_badge(badge))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py", line 217, in __async_extract_entities_from_badge
return set(config["entities"])
^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
2023-08-16 17:52:28.292 DEBUG (MainThread) [custom_components.spook] Spook is inspecting: automation_unknown_entity_references
2023-08-16 17:52:28.314 DEBUG (MainThread) [custom_components.spook] Spook is inspecting: automation_unknown_area_references
2023-08-16 17:52:28.330 DEBUG (MainThread) [custom_components.spook] Spook is inspecting: automation_unknown_device_references
2023-08-16 17:52:28.337 DEBUG (MainThread) [custom_components.spook] Spook is inspecting: script_unknown_entity_references
2023-08-16 17:52:28.356 DEBUG (MainThread) [custom_components.spook] Spook is inspecting: script_unknown_area_references
2023-08-16 17:52:28.358 DEBUG (MainThread) [custom_components.spook] Spook is inspecting: script_unknown_device_references
2023-08-16 17:52:28.361 DEBUG (MainThread) [custom_components.spook] Spook is inspecting: integration_unknown_source
2023-08-16 17:52:28.378 DEBUG (MainThread) [custom_components.spook] Spook is inspecting: group_unknown_members
2023-08-16 17:52:28.398 DEBUG (MainThread) [custom_components.spook] Spook is inspecting: switch_as_x_unknown_source
2023-08-16 17:52:38.273 DEBUG (MainThread) [custom_components.spook] Spook is inspecting: lovelace_unknown_entity_references
2023-08-16 17:52:38.277 DEBUG (MainThread) [custom_components.spook] Config for dashboard lovelace not found, skipping
2023-08-16 17:52:38.277 ERROR (MainThread) [custom_components.spook] Unexpected exception from <function AbstractSpookRepair.async_activate.<locals>._async_inspect at 0xffff634a5580>
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 116, in _handle_timer_finish
await task
File "/config/custom_components/spook/repairs.py", line 126, in _async_inspect
await self.async_inspect()
File "/config/custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py", line 112, in async_inspect
for entity_id in self.__async_extract_entities(config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py", line 159, in __async_extract_entities
entities.update(self.__async_extract_entities_from_badge(badge))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py", line 217, in __async_extract_entities_from_badge
return set(config["entities"])
^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
2023-08-16 17:52:38.304 DEBUG (MainThread) [custom_components.spook] Spook is inspecting: automation_unknown_entity_references
2023-08-16 17:52:38.343 DEBUG (MainThread) [custom_components.spook] Spook is inspecting: script_unknown_entity_references
2023-08-16 17:53:05.212 DEBUG (MainThread) [custom_components.spook] Spook is inspecting: lovelace_unknown_entity_references
2023-08-16 17:53:05.215 DEBUG (MainThread) [custom_components.spook] Config for dashboard lovelace not found, skipping
2023-08-16 17:53:05.215 DEBUG (MainThread) [custom_components.spook] Spook is inspecting: automation_unknown_entity_references
2023-08-16 17:53:05.220 DEBUG (MainThread) [custom_components.spook] Spook is inspecting: script_unknown_entity_references
2023-08-16 17:53:05.224 ERROR (MainThread) [custom_components.spook] Unexpected exception from <function AbstractSpookRepair.async_activate.<locals>._async_inspect at 0xffff634a5580>
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 116, in _handle_timer_finish
await task
File "/config/custom_components/spook/repairs.py", line 126, in _async_inspect
await self.async_inspect()
File "/config/custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py", line 112, in async_inspect
for entity_id in self.__async_extract_entities(config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py", line 159, in __async_extract_entities
entities.update(self.__async_extract_entities_from_badge(badge))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py", line 217, in __async_extract_entities_from_badge
return set(config["entities"])
^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
2023-08-16 17:53:48.611 DEBUG (MainThread) [custom_components.spook] Spook is inspecting: lovelace_unknown_entity_references
2023-08-16 17:53:48.615 DEBUG (MainThread) [custom_components.spook] Config for dashboard lovelace not found, skipping
2023-08-16 17:53:48.615 DEBUG (MainThread) [custom_components.spook] Spook is inspecting: automation_unknown_entity_references
2023-08-16 17:53:48.620 DEBUG (MainThread) [custom_components.spook] Spook is inspecting: script_unknown_entity_references
2023-08-16 17:53:48.623 ERROR (MainThread) [custom_components.spook] Unexpected exception from <function AbstractSpookRepair.async_activate.<locals>._async_inspect at 0xffff634a5580>
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 116, in _handle_timer_finish
await task
File "/config/custom_components/spook/repairs.py", line 126, in _async_inspect
await self.async_inspect()
File "/config/custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py", line 112, in async_inspect
for entity_id in self.__async_extract_entities(config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py", line 159, in __async_extract_entities
entities.update(self.__async_extract_entities_from_badge(badge))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py", line 217, in __async_extract_entities_from_badge
return set(config["entities"])
^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
```

**Comment by frenck** [comment]
Nice! Thanks for reporting this one. Will look into it.

(So many different configurations possible 😵 )

../Frenck

**Comment by emufan** [comment]
HA, the world of the infinite dream.
