### ISSUE TITLE
Unexpected exception from <function AbstractSpookRepair.async_activate.<locals>._async_inspect at 0xffff867a6520>

### ISSUE THREAD

**Issue by P-Verbrugge** [frenck/spook#437]
### What version of Spook are you using?

1.3.2

### What version of Home Assistant are you using?

2023.11.0

### The problem

Log error. See log below. 

Not sure what is causing the issue.

### Anything in the logs? Paste it here!

```plain text
Logger: custom_components.spook
Source: helpers/debounce.py:114
Integration: Spook (documentation, issues)
First occurred: 16:19:39 (1 occurrences)
Last logged: 16:19:39

Unexpected exception from <function AbstractSpookRepair.async_activate.<locals>._async_inspect at 0xffff867a6520>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 114, in _handle_timer_finish
    await task
  File "/config/custom_components/spook/repairs.py", line 130, in _async_inspect
    await self.async_inspect()
  File "/config/custom_components/spook/ectoplasms/scene/repairs/unknown_entity_references.py", line 35, in async_inspect
    scenes: list[scene.HomeAssistantScene] = self.hass.data[
                                             ^^^^^^^^^^^^^^^
KeyError: 'homeassistant_scene'
```

**Comment by frenck** [comment]
Hmmm, I wonder how to reproduce this one...
