### ISSUE TITLE
Error in log

### ISSUE THREAD

**Issue by jokerigno** [frenck/spook#461]
### What version of Spook are you using?

1.3.2

### What version of Home Assistant are you using?

2023.11.3

### The problem

I found a error every 15 sec in the log. (pasted below)

### Anything in the logs? Paste it here!

```plain text
2023-12-02 23:35:22.078 ERROR (MainThread) [custom_components.spook] Unexpected exception from <function AbstractSpookRepair.async_activate.<locals>._async_inspect at 0x7f35d3598400>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 114, in _handle_timer_finish
    await task
  File "/config/custom_components/spook/repairs.py", line 130, in _async_inspect
    await self.async_inspect()
  File "/config/custom_components/spook/ectoplasms/script/repairs/unknown_entity_references.py", line 99, in async_inspect
    for entity_id in entity.script.referenced_entities
                     ^^^^^^^^^^^^^
AttributeError: 'UnavailableScriptEntity' object has no attribute 'script'
```

**Comment by frenck** [comment]
Fixed in #497
