### ISSUE TITLE
Spook isnt loading

### ISSUE THREAD

**Issue by panteLx** [frenck/spook#470]
### What version of Spook are you using?

1.3.2

### What version of Home Assistant are you using?

2023.12

### The problem

Spook isnt loading. All sensors are unavailable as well.

### Anything in the logs? Paste it here!

```
Logger: homeassistant.config_entries
Source: config_entries.py:557
First occurred: 16:30:16 (1 occurrences)
Last logged: 16:30:16

Error unloading entry Not your homie for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 557, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 89, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 205, in async_unload_entry
    await platform.async_reset()
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 768, in async_reset
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1044, in async_remove
    await self.__async_remove_impl(force_remove)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1054, in __async_remove_impl
    self._call_on_remove_callbacks()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in _call_on_remove_callbacks
    self._on_remove.pop()()
TypeError: 'NoneType' object is not callable
```

```plain text
Logger: homeassistant.core
Source: core.py:1263
First occurred: 16:30:16 (53 occurrences)
Last logged: 16:30:16

Unable to remove unknown job listener (<Job onetime listen homeassistant_started <function HomeAssistantSpookSensorEntity.async_added_to_hass.<locals>._update_state at 0x7f4997207a60> HassJobType.Callback <function HomeAssistantSpookSensorEntity.async_added_to_hass.<locals>._update_state at 0x7f4997207b00>>, None, False)
Unable to remove unknown job listener (<Job onetime listen homeassistant_started <function HomeAssistantSpookSensorEntity.async_added_to_hass.<locals>._update_state at 0x7f4997207c40> HassJobType.Callback <function HomeAssistantSpookSensorEntity.async_added_to_hass.<locals>._update_state at 0x7f4997207ce0>>, None, False)
Unable to remove unknown job listener (<Job onetime listen homeassistant_started <function HomeAssistantSpookSensorEntity.async_added_to_hass.<locals>._update_state at 0x7f4997207e20> HassJobType.Callback <function HomeAssistantSpookSensorEntity.async_added_to_hass.<locals>._update_state at 0x7f4997207ec0>>, None, False)
Unable to remove unknown job listener (<Job onetime listen homeassistant_started <function HomeAssistantSpookSensorEntity.async_added_to_hass.<locals>._update_state at 0x7f4997250040> HassJobType.Callback <function HomeAssistantSpookSensorEntity.async_added_to_hass.<locals>._update_state at 0x7f49972500e0>>, None, False)
Unable to remove unknown job listener (<Job onetime listen homeassistant_started <function HomeAssistantSpookSensorEntity.async_added_to_hass.<locals>._update_state at 0x7f4997250220> HassJobType.Callback <function HomeAssistantSpookSensorEntity.async_added_to_hass.<locals>._update_state at 0x7f49972502c0>>, None, False)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1263, in _async_remove_listener
    self._listeners[event_type].remove(filterable_job)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'homeassistant_started'
```

**Comment by panteLx** [comment]
fixed by restarting HASS
