### ISSUE TITLE
AttributeError: 'UnavailableScriptEntity' object has no attribute 'script' - Unexpected exception from <function AbstractSpookRepair.async_activate.<locals>._async_inspect

### ISSUE THREAD

**Issue by controlcde** [frenck/spook#476]
### What version of Spook are you using?

1.4.0

### What version of Home Assistant are you using?

2023.12.1

### The problem

The error messages occurs with Spook 1.4.0 and upgrading to 2023.12.0. After every restart I got three similar error messages.

### Anything in the logs? Paste it here!

```plain text
Logger: custom_components.spook
Source: helpers/debounce.py:114
Integration: Spook (documentation, issues)
First occurred: 09:42:45 (15 occurrences)
Last logged: 09:50:26

Unexpected exception from <function AbstractSpookRepair.async_activate.<locals>._async_inspect at 0x7fb5a5b876a0>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 114, in _handle_timer_finish
    await task
  File "/config/custom_components/spook/repairs.py", line 130, in _async_inspect
    await self.async_inspect()
  File "/config/custom_components/spook/ectoplasms/script/repairs/unknown_entity_references.py", line 99, in async_inspect
    for entity_id in entity.script.referenced_entities
                     ^^^^^^^^^^^^^
AttributeError: 'UnavailableScriptEntity' object has no attribute 'script'
```

**Comment by shiner66** [comment]
Getting the same issue

**Comment by frenck** [comment]
Thanks for the report!

Fixed it in the current dev, and will ship it with the next release.

../Frenck
