### ISSUE TITLE
From 2.2.0 version i have those errors in Ha logs

### ISSUE THREAD

**Issue by pbranly** [frenck/spook#608]
### What version of Spook are you using?

2.2.0

### What version of Home Assistant are you using?

2024.2.1

### The problem

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 114, in _handle_timer_finish
    await task
  File "/config/custom_components/spook/repairs.py", line 134, in _async_inspect
    await self.async_inspect()
  File "/config/custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py", line 67, in async_inspect
    _async_find_services_in_sequence(
  File "/config/custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py", line 120, in _async_find_services_in_sequence
    _async_find_services_in_sequence(called_services, choice[CONF_SEQUENCE])
  File "/config/custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py", line 120, in _async_find_services_in_sequence
    _async_find_services_in_sequence(called_services, choice[CONF_SEQUENCE])
  File "/config/custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py", line 120, in _async_find_services_in_sequence
    _async_find_services_in_sequence(called_services, choice[CONF_SEQUENCE])
  File "/config/custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py", line 125, in _async_find_services_in_sequence
    _async_find_services_in_sequence(called_services, step[CONF_THEN])
  File "/config/custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py", line 136, in _async_find_services_in_sequence
    _async_find_services_in_sequence(called_services, step[CONF_SEQUENCE])

### Anything in the logs? Paste it here!

```plain text
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 114, in _handle_timer_finish
    await task
  File "/config/custom_components/spook/repairs.py", line 134, in _async_inspect
    await self.async_inspect()
  File "/config/custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py", line 67, in async_inspect
    _async_find_services_in_sequence(
  File "/config/custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py", line 120, in _async_find_services_in_sequence
    _async_find_services_in_sequence(called_services, choice[CONF_SEQUENCE])
  File "/config/custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py", line 120, in _async_find_services_in_sequence
    _async_find_services_in_sequence(called_services, choice[CONF_SEQUENCE])
  File "/config/custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py", line 120, in _async_find_services_in_sequence
    _async_find_services_in_sequence(called_services, choice[CONF_SEQUENCE])
  File "/config/custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py", line 125, in _async_find_services_in_sequence
    _async_find_services_in_sequence(called_services, step[CONF_THEN])
  File "/config/custom_components/spook/ectoplasms/automation/repairs/unknown_service_references.py", line 136, in _async_find_services_in_sequence
    _async_find_services_in_sequence(called_services, step[CONF_SEQUENCE])
```

**Comment by frenck** [comment]
Thanks! That is a bug, which I've fixed in #607 

This will be shipped with the next version.

../Frenck
