### ISSUE TITLE
Error while setting up spook platform for switch, sensor, event & button

### ISSUE THREAD

**Issue by jeffjumper** [frenck/spook#748]
### What version of Spook are you using?

3.0.0

### What version of Home Assistant are you using?

2024.5.0

### The problem

I'm seeing 4 errors in my HA core log on startup. There's one each for switch, sensor, event & button.

In case it matters, I installed Spook in a directory under /config/custom_components (I don't have HACS installed). It used to work fine that way on older versions. I'm running HAOS on a Proxmox vm.

Thanks for looking at it! I'm glad Spook is finally my homie now 👻

### Anything in the logs? Paste it here!

```plain text
2024-05-01 18:01:48.455 ERROR (MainThread) [homeassistant.components.switch] Error while setting up spook platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
await asyncio.shield(awaitable)
File "/config/custom_components/spook/switch.py", line 23, in async_setup_entry
await async_forward_platform_entry_setups_to_ectoplasm(
File "/config/custom_components/spook/util.py", line 98, in async_forward_platform_entry_setups_to_ectoplasm
await hass.async_add_import_executor_job(_load_all_ectoplasm_platform_modules)
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/spook/util.py", line 95, in _load_all_ectoplasm_platform_modules
modules.append(importlib.import_module(f".{module_path}", __package__))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/util/loop.py", line 144, in protected_loop_func
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 995, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/config/custom_components/spook/ectoplasms/cloud/switch.py", line 26, in <module>
@dataclass(frozen=True, kw_only=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dataclasses.py", line 1256, in wrap
return _process_class(cls, init, repr, eq, order, unsafe_hash,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dataclasses.py", line 1029, in _process_class
raise TypeError('cannot inherit frozen dataclass from a '
TypeError: cannot inherit frozen dataclass from a non-frozen one
```

**Comment by frenck** [comment]
Please upgrade to 3.0.1 😀
