### ISSUE TITLE
Update from 3..0.1 to 3.1.0; update/download doesn't stop.

### ISSUE THREAD

**Issue by deon-dup** [frenck/spook#842]
### What version of Spook are you using?

3.1.0

### What version of Home Assistant are you using?

2024.9.0

### The problem

Two issue, but definitely related.

1. I tried to update from 3.0.1 to 3.1.0, but the Update button, just continues to run. Deleted Spook, re-downloaded, same issue. I eventually quite the download, checked that all the files have been downloaded, and restarted. I can install Spook from Devices and Integration, restart, and then problem 2 starts.
2. Spook failed to setup, need to check the logs. Get the following in the logs:

- "ModuleNotFoundError: No module named 'custom_components.spook.spook-3'"

### Anything in the logs? Paste it here!

```plain text
Logger: homeassistant.config_entries
Source: config_entries.py:604 
First occurred: 10:10:49 AM (1 occurrences) 
Last logged: 10:10:49 AM

Error setting up entry Your homie for spook
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spook/__init__.py", line 84, in async_setup_entry
    await async_forward_setup_entry(hass, entry)
  File "/config/custom_components/spook/util.py", line 70, in async_forward_setup_entry
    await hass.async_add_import_executor_job(_load_all_ectoplasm_modules)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/spook/util.py", line 65, in _load_all_ectoplasm_modules
    module = importlib.import_module(f".{module_path}", __package__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.spook.spook-3'
```

**Comment by Phipps78** [comment]
Same problem

**Comment by snormonster** [comment]
Also have this problem on a new install of Spook v3.1.0 on latest Home Assistant

**Comment by snormonster** [comment]
I think this happens if something went wrong with downloading it in HACS, I deleted it there and redownloaded it, and removed and re-added the integration, and then it worked.

**Comment by frenck** [comment]
Seems to be an external installation / integration management issue. There is not much Spook can do about it.

../Frenck
